### ISSUE TITLE
mithril request API is difficult to test

### ISSUE THREAD

**Issue by ytetsuro** [MithrilJS/mithril.js#1998]
mithril request API is difficult to test

I attempted to do unit tests using mithril and ospec, but in the following case we could not test with require cache.
everyone, How do you solved this problem?

A.js
```javascript
const m = require('mithril');

module.exports = class A {
  constructor() {
    this.hoge = [];
  }

  get() {
    return m.request({
      method: 'GET',
      url: '/api/v1/users/:id',
      data: { id: 1, name: 'test' },
    }).then((result) => {
      this.hoge.push(result);
    });
  }
};

```

B.js
```javascript
const m = require('mithril');

module.exports = class B {
...
```

ATest.js
```javascript
const o = require('mithril/ospec/ospec');
const browserMock = require('mithril/test-utils/browserMock.js');

o.spec('A', () => {
  let a;

  o.beforeEach(() => {
    global.window = browserMock();
    global.document = global.window.document;

    const A = require('../A');
    a = new A();
  });

  o('Acquire server', (done) => {
    global.window.$defineRoutes({
      'GET /api/v1/users/1': () => {
        return {
          status: 200,
          responseText: JSON.stringify({ type: 'Foo', id: 1192 }),
        };
      },
    });

    a.get().then(() => {
      o(a.hoge[0].type).equals('Foo');
      done();
    });
  });
});
```

BTest.js
```javascript
const o = require('mithril/ospec/ospec');
const browserMock = require('mithril/test-utils/browserMock.js');

o.spec('B', () => {
  let b;

  o.beforeEach(() => {
    global.window = browserMock();
    global.document = global.window.document;

    const B = require('../B');
    b = new B();
  });

  o('Acquire server', (done) => {
    global.window.$defineRoutes({
      'GET /api/v2/users/1': () => {
        return {
          status: 200,
          responseText: JSON.stringify({ type: 'Foo', id: 1192 }),
        };
      },
    });

    b.get().then(() => {
      o(b.hoge[0].type).equals('Foo');
      done();
    });
  });
});
```

## Expected Behavior

All green

## Current Behavior

```shell
$ npm run test

> hoge@1.0.0 test /Volumes/Transcend/dev/hoge
> ospec

Possible unhandled promise rejection: Error: server error, most likely the URL was not defined /api/v2/users/1
    at Object.deserialize (/Volumes/Transcend/dev/hoge/node_modules/mithril/mithril.js:358:20)
    at XMLHttpRequest.xhr.onreadystatechange (/Volumes/Transcend/dev/hoge/node_modules/mithril/mithril.js:293:82)
    at Immediate._onImmediate (/Volumes/Transcend/dev/hoge/node_modules/mithril/test-utils/xhrMock.js:58:63)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
B > Acquire server:
async test timed out

    at ontimeout (timers.js:488:11)

3 assertions completed in 229ms, of which 1 failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hoge@1.0.0 test: `ospec`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hoge@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ytetsuro/.npm/_logs/2017-10-19T19_11_29_200Z-debug.log
```

## Possible Solution

delete mithril from require cache.
Also, I do not think that deleting require cache is a good code.

## Context

mithril request API is difficult to test

## Your Environment

* Version used: 1.1.5
* Browser Name and version: None
* Operating System and version (desktop or mobile): mac OS 10.12.6

**Comment by pygy** [comment]
@ytetsuro sorry we let this one slip... I'm not really familiar with the XHR mock, did you manage to find a clean solution to you problem, or do we need to dig in?

**Comment by Moschn** [comment]
I encountered the same problem. As soon as the tests are split up into two files the following error is 
thrown: `Possible unhandled promise rejection: Error: server error, most likely the URL was not defined`.

Both test files work on their own but if both exist, then no test that uses `m.request` completes successfully.

The method that I use for `browserMock` is shown on [mithril.js.org/testing.html](https://mithril.js.org/testing.html#running-mithril-in-a-non-browser-environment).

**Comment by ytetsuro** [comment]
@pygy 

> sorry we let this one slip... I'm not really familiar with the XHR mock, did you manage to find a clean solution to your problem, or do we need to dig in?

I am sorry to leave it.
I made a PR of fix.

**Comment by pygy** [comment]
Ok, now I understand the issue.

Mithril binds itself to the `window` object that is defined when it is first loaded, causing issues when trying to create fresh mock instances...

A solution would be to use a singleton pattern for defining the mocks in your test suite.

```JS
// mocks.js

var loaded = false

module.exports.reset = function() {
  if (!loaded) {
    loaded = true
    global.window = browserMock();
    global.document = global.window.document;
  }
  global.document.documentElement = global.document.createElement("html")
  global.document.documentElement.appendChild(global.document.createElement("head"))
  global.document.body = global.document.createElement("body")
  global.document.documentElement.appendChild(global.document.body)
  global.document.focus()

  global.window.$defineRoutes({})

  // maybe some code to reset the history mock?

  return global.window
}
```

Then in your test code:
```JS
var mocks = require("./my-test-utils/mocks")
o.spec("...", function() {
  var window
  o.beforeEach(function(){
    window = mocks.reset()
    // ...
  })
  // ...
})
```

**Comment by ytetsuro** [comment]
I understand.

Thanks.

By the way, is this a bug label, but is it a bug?

**Comment by pygy** [comment]
Indeed, it wasn't a bug :-)

Can we close this?

**Comment by pygy** [comment]
@ytetsuro  Ok from your comment in #2233 I assume I can close this.

**Comment by ytetsuro** [comment]
@pygy 

Thanks close.
