### ISSUE TITLE
Ospec failing test ("the done parser > tolerates comments")

### ISSUE THREAD

**Issue by vrimar** [MithrilJS/mithril.js#2351]
Test fails with message:
```
the done parser > tolerates comments:
true
  should equal
false
    at c:\Users\Vasil\Documents\Projects\mithril.js\ospec\tests\test-ospec.js:688:12
```

Stack trace: 
```
Error
    at next (c:\Users\Vasil\Documents\Projects\mithril.js\ospec\ospec.js:171:15)
    at series (c:\Users\Vasil\Documents\Projects\mithril.js\ospec\ospec.js:124:4)
    at c:\Users\Vasil\Documents\Projects\mithril.js\ospec\ospec.js:114:38
    at next (c:\Users\Vasil\Documents\Projects\mithril.js\ospec\ospec.js:176:7)
    at series (c:\Users\Vasil\Documents\Projects\mithril.js\ospec\ospec.js:124:4)
    at test (c:\Users\Vasil\Documents\Projects\mithril.js\ospec\ospec.js:108:4)
    at Function.o.run (c:\Users\Vasil\Documents\Projects\mithril.js\ospec\ospec.js:93:3)
    at c:\Users\Vasil\Documents\Projects\mithril.js\ospec\tests\test-ospec.js:687:11
    at next (c:\Users\Vasil\Documents\Projects\mithril.js\ospec\ospec.js:188:15)
    at series (c:\Users\Vasil\Documents\Projects\mithril.js\ospec\ospec.js:124:4)
```

Clean stack trace: 
```
//huuu()` should be called at least once
    at c:\Users\Vasil\Documents\Projects\mithril.js\ospec\tests\test-ospec.js:677:3
```

**Comment by isiahmeadows** [comment]
Closing since I'm not seeing this anymore.
