### ISSUE TITLE
Ospec doesn't handle relative paths on Windows

### ISSUE THREAD

**Issue by Manidos** [MithrilJS/mithril.js#2489]
Platform: Windows 10, 64 bit
Node:  v10.16.0
NPM:  6.9.0

I'm trying to reproduce a testing setup from official [docs](https://mithril.js.org/testing.html). 
When I run `npm test` either from `powershell` or `cmd` I get an error:

```
> ospec --require ./test-setup.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './test-setup.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.resolve (internal/modules/cjs/helpers.js:33:19)
    at C:\Users\Predator\Desktop\dev\JS\mithril repos\test-test\node_modules\ospec\bin\ospec:33:31
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\Predator\Desktop\dev\JS\mithril repos\test-test\node_modules\ospec\bin\ospec:31:15)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! Test failed.  See above for more details.
```

Then  I change a line in `package.json` from
`"test": "ospec --require ./test-setup.js"`
to
`"test": "ospec --require ../../../test-setup.js" `

And I get another error caused by `require("mithril")` line in `test-setup.js` (there was no mention to install `mithrill` in the docs)

Then I do `npm install --save-dev mithril`

And I get another error 

```
Error: Cannot find module '../../../test-setup.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.resolve (internal/modules/cjs/helpers.js:33:19)
    at C:\Users\Predator\Desktop\dev\JS\mithril repos\test-test\node_modules\mithril\ospec\bin\ospec:33:31
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\Predator\Desktop\dev\JS\mithril repos\test-test\node_modules\mithril\ospec\bin\ospec:31:15)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3
```

Then  I change a line in `package.json` from
`"test": "ospec --require ../../../test-setup.js"`
to
`"test": "ospec --require ../../../../test-setup.js" `

And I get output:

```
> ospec --require ../../../../test-setup.js

––––––
All 0 assertions passed in 5ms
```

However expected output according to docs is:

```
––––––
All 1 assertions passed in 0ms
```

**Comment by onlyskin** [comment]
I'm seeing the same issue on OSX

It seems to be caused by this line https://github.com/MithrilJS/mithril.js/blob/next/ospec/bin/ospec#L33

The `basedir` option passed to `require.resolve` doesn't seem to be supported for the node implementation of `require` (https://nodejs.org/api/modules.html#modules_require_resolve_request_options)

Instead, there is a paths argument. If I replace `{basedir: cwd}` with `{paths: [cwd]}`, it works for me.

**Comment by onlyskin** [comment]
I have raised https://github.com/MithrilJS/mithril.js/pull/2511 to fix this
