### ISSUE TITLE
v2.2.2 -> v2.2.3 Conditional components generate errors?

### ISSUE THREAD

**Issue by thequailman** [MithrilJS/mithril.js#2990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Mithril.js Version

v2.2.3+

### Browser and OS

Happy dom

### Code

```javascript
N/A
```

### Steps to Reproduce

Upgrade mithril from 2.2.2 to 2.2.3+

### Expected Behavior

No errors/breaking of rendering.

### Observed Behavior

I see these errors on a bunch of my tests after upgrading from 2.2.2 to 2.2.3 (problem still exists in 2.2.10), and it breaks rendering.  This does NOT happen at all on 2.2.2.

```
TypeError: Cannot destructure property 'nextSibling' of 'dom' as it is null.
    at domFor (/node_modules/mithril/render/domFor.js:7:10)
    at domFor.next (<anonymous>)
    at removeDOM (/node_modules/mithril/render/render.js:653:13)
    at removeNode (/node_modules/mithril/render/render.js:613:4)
    at updateNodes (/node_modules/mithril/render/render.js:294:26)
    at updateElement (/node_modules/mithril/render/render.js:459:4)
    at updateNode (/node_modules/mithril/render/render.js:409:15)
    at updateNodes (/node_modules/mithril/render/render.js:295:11)
    at updateElement (/node_modules/mithril/render/render.js:459:4)
    at updateNode (/node_modules/mithril/render/render.js:409:15)

stderr | src/lib/components/component.test.ts > Component
DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at HTMLDivElement.[insertBefore] (file:////node_modules/happy-dom/src/nodes/node/Node.ts:641:10)
    at HTMLDivElement.[insertBefore] (file:////node_modules/happy-dom/src/nodes/element/Element.ts:1304:57)
    at HTMLDivElement.insertBefore (file:////node_modules/happy-dom/src/nodes/node/Node.ts:422:43)
    at HTMLDivElement.[insertBefore] (file:////node_modules/happy-dom/src/nodes/node/Node.ts:625:10)
    at HTMLDivElement.[insertBefore] (file:////node_modules/happy-dom/src/nodes/element/Element.ts:1304:57)
    at HTMLDivElement.insertBefore (file:////node_modules/happy-dom/src/nodes/node/Node.ts:422:43)
    at insertDOM (/node_modules/mithril/render/render.js:564:35)
    at createFragment (/node_modules/mithril/render/render.js:110:3)
    at createNode (/node_modules/mithril/render/render.js:67:15)
    at createComponent (/node_modules/mithril/render/render.js:161:4)
```

This could be a happy-dom issue, but I'd love to be able to provide a reproducible thing that doesn't involve a ton of libraries.  Is there any logging I could add to `render.js` or `domFor.js` to narrow down the issue or what el it's acting on?

**Comment by dead-claudia** [comment]
Could you provide code to reproduce?

**Comment by kfule** [comment]
> DOMException: Failed to execute 'insertBefore' on 'Node'

It seems there was an issue a while ago regarding insertBefore of happydom.

https://github.com/capricorn86/happy-dom/issues/1429

**Comment by thequailman** [comment]
This ended up being a happy-dom bug #https://github.com/capricorn86/happy-dom/issues/1793
